---
title: "Chapter 2 Notes"
format: html
editor: visual
---

## Aaron Freeman \| Feb 1st, 2024

### swcarpentry r-novice tutorial

#### https://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro.html#before-starting-the-workshop

### Project Management with RStudio

#### Why its good to have a neat project layout

-   It will help ensure the integrity of data
-   It makes it simpler to share your code with someone else
-   It allows you to easily upload your code with you manuscript submission
-   It makes it easier to pick the project back up after a break

### Best practices for project organization

#### Treat data as read only

This is probably the most important goal of setting up a project. Avoid modifying data like you would in excel. This ensures that the data is traceable and reliable. Therefore, it is a good idea to treat the data as "read-only"

#### Data Cleaning

Data will not always be ready to be used in R. It will need preprocessing to get into a format R will find useful. Storing these scrips in a separate folder, and creating a second "read-only" folder to hold the "cleaned" data sets can prevent confusion between the two sets.

#### Treat generated output as disposable

Anything generated by your scrips should be treated as disposable: it should be able to be regenerated from your scripts. Having an output folder with different sub-directories for each separate analysis makes it easier later. Since many analyses are exploratory and don't end up being used and some of the analyses get shared between projects.

### Tip for good scientific computing practices

-   Put each project in its own directory, which is named after the project.
-   Put text documents associated with the project in the doc directory
-   Put raw data and metadata in the data directory, and files generated during cleanup and analysis in a results directory.
-   Put source for the project's scripts and programs in the src directory, and programs brought in from elsewhere or compiled locally in the bin directory.
-   Name all files to reflect their content or function
